name: selenium_teams
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.10
  - pip

  # Dependencies available on Conda
  - selenium=4.22.0
  - python-dotenv=1.0.1
  - keyboard=0.13.5

  # Dependencies to be installed with Pip
  - pip:
    - undetected-chromedriver==3.5.5
